name: 30
timestamp: 0
preset:
  image: 'gantry-admin://images/layouts/home.png'
  name: home_positions
  timestamp: 1441941680
positions:
  header-a: 'Header A'
  slideshow-b: 'Slideshow B'
  showcase-a: 'Showcase A'
  showcase-b: 'Showcase B'
  sidebar: Sidebar
  mainbar-a: 'Mainbar A'
  mainbar-b: 'Mainbar B'
  mainbar-c: 'Mainbar C'
  aside: Aside
  expanded-a: 'Expanded A'
  bottom-a: 'Bottom A'
  footer-a: 'Footer A'
  footside-a: 'Footside A'
  footside-b: 'Footside B'
  footside-c: 'Footside C'
