name: 26
timestamp: 0
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: typography
  timestamp: 1446851170
positions:
  top-a: 'Top A'
  top-b: 'Top B'
  top-c: 'Top C'
  header-a: 'Header A'
  header-b: 'Header B'
  header-c: 'Header C'
  slideshow-a: 'Slideshow A'
  slideshow-b: 'Slideshow B'
  slideshow-c: 'Slideshow C'
  showcase-a: 'Showcase A'
  showcase-b: 'Showcase B'
  showcase-c: 'Showcase C'
  above-a: 'Above A'
  above-b: 'Above B'
  above-c: 'Above C'
  utility-a: 'Utility A'
  utility-b: 'Utility B'
  utility-c: 'Utility C'
  feature-a: 'Feature A'
  feature-b: 'Feature B'
  feature-c: 'Feature C'
  sidebar: Sidebar
  mainbar-a: 'Mainbar A'
  mainbar-b: 'Mainbar B'
  'mainbar -c': 'Mainbar C'
  aside: Aside
  expanded-a: 'Expanded A'
  expanded-b: 'Expanded B'
  expanded-c: 'Expanded C'
  extension-a: 'Extension A'
  extension-b: 'Extension B'
  extension-c: 'Extension C'
  bottom-a: 'Bottom A'
  bottom-b: 'Bottom B'
  bottom-c: 'Bottom C'
  footer-a: 'Footer A'
  footer-b: 'Footer B'
  footer-c: 'Footer C'
  footside-a: 'Footside A'
