ordering:
  home: ''
  features:
    overview: ''
    typography: ''
    block-variations: ''
    2015-05-29-15-29-38: ''
    2015-05-29-15-30-21: ''
  pages:
    -
      about-us: ''
      pricing: ''
      portfolio: ''
      our-team: ''
      services: ''
      clients: ''
      blog: ''
    -
      contact: ''
      error: ''
      coming-soon: ''
      offline: ''
  styles:
    __particle-muOvm: ''
  2015-06-01-09-45-25: ''
items:
  home:
    id: 101
    hash: ''
    width: auto
    class: ''
  features:
    id: 104
    hash: ''
    width: auto
    class: ''
  features/2015-05-29-15-29-38:
    id: 108
    hash: ''
    width: auto
    class: ''
  pages:
    id: 110
    hash: ''
    dropdown: fullwidth
    width: 360px
    class: ''
  styles:
    id: 123
    hash: ''
    dropdown: fullwidth
    width: auto
    class: ''
  2015-06-01-09-45-25:
    id: 124
    hash: ''
    width: auto
    class: ''
  styles/__particle-muOvm:
    type: particle
    particle: custom
    title: 'Custom HTML'
    options:
      particle:
        enabled: '1'
        html: "<div class=\"g-grid g-preset-thumbnails\">\n    <div class=\"g-block\">\n        <div class=\"g-content\">\n            <a href=\"?presets=preset1\">\n                <img src=\"images/rocketlauncher/styles/preset1.jpg\" alt=\"Preset 1\">\n                <br>\n                <span>Preset 1</span>\n            </a>\n        </div>\n    </div>\n    <div class=\"g-block\">\n        <div class=\"g-content\">\n            <a href=\"?presets=preset2\">\n                <img src=\"images/rocketlauncher/styles/preset2.jpg\" alt=\"Preset 2\">\n                <br>\n                <span>Preset 2</span>\n            </a>\n        </div>\n    </div>\n    <div class=\"g-block\">\n        <div class=\"g-content\">\n            <a href=\"?presets=preset3\">\n                <img src=\"images/rocketlauncher/styles/preset3.jpg\" alt=\"Preset 3\">\n                <br>\n                <span>Preset 3</span>\n            </a>\n        </div>\n    </div>\n    <div class=\"g-block\">\n        <div class=\"g-content\">\n            <a href=\"?presets=preset4\">\n                <img src=\"images/rocketlauncher/styles/preset4.jpg\" alt=\"Preset 4\">\n                <br>\n                <span>Preset 4</span>\n            </a>\n        </div>\n    </div>\n    <div class=\"g-block\">\n        <div class=\"g-content\">\n            <a href=\"?presets=preset5\">\n                <img src=\"images/rocketlauncher/styles/preset5.jpg\" alt=\"Preset 5\">\n                <br>\n                <span>Preset 5</span>\n            </a>\n        </div>\n    </div>\n    <div class=\"g-block\">\n        <div class=\"g-content\">\n            <a href=\"?presets=preset6\">\n                <img src=\"images/rocketlauncher/styles/preset6.jpg\" alt=\"Preset 6\">\n                <br>\n                <span>Preset 6</span>\n            </a>\n        </div>\n    </div>\n</div>"
      block:
        extra: {  }
