name: 24
timestamp: 0
preset:
  image: 'gantry-admin://images/layouts/home.png'
  name: home_positions
  timestamp: 1441941680
positions:
  header-a: 'Header A'
  slideshow-a: 'Module Position'
  slideshow-a-below: 'Slideshow A Below'
  slideshow-b: 'Slideshow B'
  slideshow-c-above: 'Slideshow C Above'
  slideshow-c: 'Slideshow C'
  slideshow-c-below: 'Slideshow C Below'
  showcase-a: 'Showcase A'
  showcase-b: 'Showcase B'
  above-a: 'Above A'
  above-b: 'Above B'
  above-c: 'Above C'
  utility-a: 'Utility A'
  feature-a: 'Feature A'
  sidebar: Sidebar
  mainbar-a: 'Mainbar A'
  mainbar-b: 'Mainbar B'
  mainbar-c: 'Mainbar C'
  aside: Aside
  expanded-a: 'Expanded A'
  extension-a: 'Extension A'
  extension-b: 'Extension B'
  bottom-a: 'Bottom A'
  footer-a: 'Footer A'
  footside-a: 'Footside A'
  footside-b: 'Footside B'
  footside-c: 'Footside C'
